// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdb3_PlXof9huJNmzWRgbwmB0eGWKi1UU',
    appId: '1:1074540941339:android:23d305e157886df2e328be',
    messagingSenderId: '1074540941339',
    projectId: 'flutter-proj-12a36',
    storageBucket: 'flutter-proj-12a36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoaKwf7Y2NTbprKzKGUUlPinG25izU59s',
    appId: '1:1074540941339:ios:df2872f289841b60e328be',
    messagingSenderId: '1074540941339',
    projectId: 'flutter-proj-12a36',
    storageBucket: 'flutter-proj-12a36.firebasestorage.app',
    iosBundleId: 'com.nti.toDoApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnSgFS10x9aZ-ddxnXU1WsBw6woVPffG0',
    appId: '1:1074540941339:web:63f0843884414e27e328be',
    messagingSenderId: '1074540941339',
    projectId: 'flutter-proj-12a36',
    authDomain: 'flutter-proj-12a36.firebaseapp.com',
    storageBucket: 'flutter-proj-12a36.firebasestorage.app',
    measurementId: 'G-0XDNEX3T54',
  );

}